name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies (if any)
      run: |
        echo "No dependencies to install"
    - name: Success Message
      run: echo "🎉 GitHub Actions workflow ran successfully!"




